services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: brivo_scim_app
    restart: unless-stopped

    ports:
      - '3000:3000'

    environment:
      NODE_ENV: production
      PORT: 3000

      DB_HOST: db
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: admin
      DB_NAME: brivo_scim

    depends_on:
      db:
        condition: service_healthy

    healthcheck:
      test: ['CMD', 'wget', '--no-verbose', '--tries=1', '--spider', 'http://localhost:3000/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

    networks:
      - brivo_network

  db:
    image: postgres:18
    container_name: brivo_scim_db
    restart: unless-stopped

    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: brivo_scim

    ports:
      - '5432:5432'

    volumes:
      - brivo_scim_db_data:/var/lib/postgresql

    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U admin -d brivo_scim']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

    networks:
      - brivo_network

networks:
  brivo_network:
    driver: bridge

volumes:
  brivo_scim_db_data: